export const GET_NEW_BOOK = "GET_NEW_BOOKS";
export const GET_HOT_BOOK = "GET_HOT_BOOKS";
export const GET_RECOMMEND_BOOK = "GET_RECOMMEND_BOOKS";
export const DISFAVOR = "DISFAVOR";

export const GET_HOMEPAGE = "GET_HOMEPAGE";
export const GET_MARKETPLACE = "GET_MARKETPLACE";
